name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Release
        run: cargo build --release --features=no_console

      - name: Run tests
        run: cargo test --verbose

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: GAT-GWM
          path: target/release/gat-gwm

